#!/bin/sh

echo KNOTEDITOR_ROOT=$1
echo KNOTEDITOR_BIN=\$KNOTEDITOR_ROOT/bin
echo KNOTEDITOR_DATA=\$KNOTEDITOR_ROOT/data
echo KNOTEDITOR_PIXMAPS=\$KNOTEDITOR_ROOT/pixmaps
echo
echo export KNOTEDITOR_ROOT KNOTEDITOR_BIN KNOTEDITOR_DATA KNOTEDITOR_PIXMAPS
echo
echo \$KNOTEDITOR_BIN/KnotEditor
