all:
	@make -C knot all
	@make -C knot/computables all
	@make -C diagram all
	@make -C seifert all

clean:
	@make -C knot .clean
	@make -C knot/computables .clean
	@make -C diagram .clean
	@make -C seifert .clean
