all:
	@make -C diagram all
	@make -C diagramEditor all
	@make -C knot all
	@make -C knotWrapper all
	@make -C knotSurface all
	@make -C computables all
	@make -C seifert all

clean:
	@make -C diagram .clean
	@make -C diagramEditor .clean
	@make -C knot .clean
	@make -C knotWrapper .clean
	@make -C knotSurface .clean
	@make -C computables .clean
	@make -C seifert .clean
