string(TIMESTAMP APP_VERSION "2.0β1")
string(TIMESTAMP TODAY "%d %b %Y")

execute_process(
        COMMAND git log -1 --format=%H
        WORKING_DIRECTORY ${CMAKE_CURRENT_LIST_DIR}
        OUTPUT_VARIABLE GIT_HASH
        OUTPUT_STRIP_TRAILING_WHITESPACE
)

